---
- name: Init
  include_tasks: "{{ role_path }}/tasks/_common/_init.yml"
  tags:
    - init

- name: Install DNS authority
  include_role:
    name: rtnp.galaxie_clans.dns
  tags:
    - install

- name: Override dns autoconf
  lineinfile:
    path: /etc/systemd/resolved.conf
    regex: >-
      ^DNS=.*$
    line: >-
      DNS=127.0.0.1
    insertafter: >-
      \[Resolve\]
  notify: Restart resolved

- name: Force networkmanager into resolved
  lineinfile:
    path: /etc/NetworkManager/NetworkManager.conf
    regex: >-
      ^dns=.*$
    line: >-
      dns=systemd-resolved
    insertafter: >-
      \[main\]
  notify: Restart networking

- name: Force networkmanager into resolved
  file:
    src: /run/NetworkManager/resolv.conf
    path: /etc/resolv.conf
    state: link
    force: true
  notify: Restart networking

- name: Extract info
  include_tasks: "{{ role_path }}/tasks/_common/_extract.yml"
  when: inventory_hostname in groups['hashistack_sre']
  tags:
    - extract

