---
- name: Render rproxy service configuration
  template:
    src: "hs.nginx.conf.j2"
    dest: "/etc/nginx/sites-available/{{ item }}.conf"
    mode: 0640
  loop: "{{ core_rproxy_nginx_managed_sites }}"

- name: Enable managed streams
  file:
    dest: "/etc/nginx/sites-enabled/{{ item }}.conf"
    src: "/etc/nginx/sites-available/{{ item }}.conf"
    state: link
  loop: "{{ core_rproxy_nginx_managed_sites }}"
  notify: Reload nginx service

- name: Manage A record for nomad load balancers
  community.general.nsupdate:
    server: "{{ ansible_default_ipv4.address }}"
    zone: "{{ public_domain }}"
    key_name: "{{ hs_dns_key.name }}"
    key_secret: "{{ hs_dns_key_secret }}"
    key_algorithm: "hmac-sha256"
    record: "apps"
    type: "A"
    ttl: 120
    value: "{{ sre_ipv4 }}"
    state: "present"
  when:
    - groups['hashistack_masters'] | length > 1
    - molecule_yml is not defined

- name: "Sync dynamic record with zone file"
  command: >-
    rndc sync -clean {{ public_domain }} IN default
  when:
    - groups['hashistack_masters'] | length > 1
    - molecule_yml is not defined
