---
collections:
  - name: community.docker
  - name: community.crypto
  - name: community.general
  - name: ansible.utils
  - name: ansible.netcommon
  - name: ansible.posix
  - name: rtnp.galaxie_clans

roles:
  - name: cloudalchemy.grafana
  - name: cloudalchemy.prometheus
