---
collections:
  - name: ansible.posix
    version: ">=1.5.1"
  - name: ansible.utils
    version: ">=2.9.0"
  - name: ansible.netcommon
    version: ">=4.1.0"

  - name: community.docker
    version: ">=3.4.0"
  - name: community.crypto
    version: ">=2.10.0"
  - name: community.general
    version: ">=6.3.0"
  - name: community.hashi_vault
    version: ">=5.0.1"

  - name: cloud.terraform
    version: "1.1.1"
  - name: rtnp.galaxie_clans
    version: "1.15.1"
