---
- name: "[LOCAL] Download Nomad release archive"
  run_once: true
  become: false
  get_url:
    url: "{{ __hs_nomad_archive_url }}"
    dest: "{{ hs_local_cache_dir }}"
    mode: 0640
  delegate_to: localhost
  tags:
    - online

- name: "Install skopeo"
  package:
    name: "skopeo"
    state: present

- name: "Download Network Docker image"
  command: >
    skopeo copy docker://gcr.io/google_containers/pause-amd64:3.1 \
    docker-archive:/var/cache/pause-amd64-3.1.tar:gcr.io/google_containers/pause-amd64:3.1
  args:
    creates: /var/cache/pause-amd64-3.1.tar
  tags:
    - online
    - molecule-notest

- name: "Download Envoy Docker image"
  command: >
    skopeo copy docker://{{ hs_nomad_connect_image }} \
    docker-archive:/var/cache/envoy-{{ hs_nomad_connect_image_version }}.tar:{{ hs_nomad_connect_image }}
  args:
    creates: /var/cache/envoy-{{ hs_nomad_connect_image_version }}.tar
  tags:
    - online
    - molecule-notest

- name: "Get CNI plugins release"
  get_url:
    url: https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-amd64-v1.1.1.tgz
    dest: /var/cache/cni-plugins-linux-amd64-v1.1.1.tgz
    mode: 0640
  tags:
    - online
