---
- name: Install dependencies for duplicity
  package:
    name: librsync-devel
    state: present

- name: Download python packages  # noqa: command-instead-of-module
  shell: >
    pip wheel --wheel-dir /var/cache/pip {{ packages_list | join(' ') }}
  tags:
    - online

