---
- name: "Create local facts directory"
  file:
    path: "/etc/ansible/facts.d"
    recurse: true
    state: directory

- name: "Create loki system group"
  group:
    name: "loki"
    system: true
    state: present

- name: "Create loki system user"
  user:
    name: "loki"
    system: true
    shell: "/usr/sbin/nologin"
    groups:
      - "loki"
    createhome: false
    home: "{{ __loki_home_dir }}"

- name: "Create loki home and data directories"
  file:
    path: "{{ _current_dir }}"
    state: directory
    owner: loki
    group: loki
    mode: 0700
  loop:
    - "{{ __loki_home_dir }}"
    - "{{ __loki_conf_dir }}"
  loop_control:
    loop_var: _current_dir