---
- name: "[LOCAL] Download alloy release archive"
  delegate_to: localhost
  run_once: true
  become: false
  get_url:
    url: "{{ __alloy_archive_url }}"
    dest: "{{ __alloy_local_archive_path }}"
    mode: 0640
  tags:
    - online

- name: Prepare
  include_tasks:
    file: "{{ role_path }}/tasks/common/_prepare.yml"
    apply:
      tags: prepare
  tags:
    - prepare


- name: Install
  include_tasks:
    file: "{{ role_path }}/tasks/common/_install.yml"
    apply:
      tags: install
  tags:
    - install

- name: Configure
  include_tasks:
    file: "{{ role_path }}/tasks/common/_configure.yml"
    apply:
      tags: configure
  tags:
    - configure