---
- name: "Prepare"
  include_tasks:
    file: "{{ role_path }}/tasks/common/_prepare.yml"
    apply:
      tags: prepare
  tags:
    - online
    - prepare

- name: "Install"
  include_tasks:
    file: "{{ role_path }}/tasks/common/_install.yml"
    apply:
      tags: install
  tags:
    - install

- name: "Configure"
  include_tasks:
    file: "{{ role_path }}/tasks/common/_configure.yml"
    apply:
      tags: configure
  tags:
    - configure

- name: "Flush"
  meta: flush_handlers

- name: "Bootstrap"
  include_tasks: "{{ role_path }}/tasks/common/_bootstrap.yml"
  when:
    - __hs_nomad_is_master
    - __hs_nomad_bootstrap_mark not in ansible_local
  tags:
    - bootstrap

- name: "Enable nomad service"
  systemd:
    name: "nomad"
    daemon_reload: true
    state: started
    enabled: true
