---
- name: Prepare
  include_tasks: _prepare.yml
  tags:
    - prepare
    - online

- name: Install
  include_tasks: _install.yml
  tags:
    - install

- name: Configure
  include_tasks: _configure.yml
  tags:
    - configure

- name: Bootstrap
  include_tasks: _bootstrap.yml
  when:
    - __hs_nomad_is_master
    - __hs_nomad_bootstrap_mark not in ansible_local
  tags:
    - bootstrap

- name: Enable nomad service
  systemd:
    name: nomad
    daemon_reload: true
    state: started
    enabled: true
