---
- name: Render rproxy service configuration
  template:
    src: "hs.nginx.conf.j2"
    dest: "/etc/nginx/sites-available/hashistack.conf"
    mode: 0640
  notify: Reload nginx service

- name: Enable managed sites
  file:
    dest: "/etc/nginx/sites-enabled/hashistack.conf"
    src: "/etc/nginx/sites-available/hashistack.conf"
    state: link
  notify: Reload nginx service

- name: Manage A record for nomad load balancers
  community.general.nsupdate:
    server: "{{ hs_nsupdate_host }}"
    zone: "{{ public_domain }}"
    key_name: "{{ hs_dns_key.name }}"
    key_secret: "{{ hs_dns_key_secret }}"
    key_algorithm: "hmac-sha256"
    record: "apps"
    type: "A"
    ttl: 120
    value: "{{ sre_ipv4 }}"
    state: "present"
  delegate_to: "{{ hs_nsupdate_delegate_to | default(inventory_hostname) }}"
  become: >-
    {{
      (hs_nsupdate_delegate_to is not defined)
      or
      (hs_nsupdate_delegate_to != 'localhost')
    }}
  when:
    - molecule_yml is not defined

- name: "Sync dynamic record with zone file"
  command: >-
    rndc sync -clean {{ public_domain }} IN default
  when:
    - molecule_yml is not defined

- name: Ensure nginx user belong to ssl-cert group
  user:
    name: nginx
    groups:
      - ssl-cert
    append: true
