---
- name: "Get nsupdate key for domain"  # noqa risky-shell-pipe
  shell: >-
    cat /etc/bind/keys/{{ hs_dns_key.name }}.conf
    | grep secret
    | cut -d '"' -f2
  register: tsig_key_sh
  changed_when: false
  when: molecule_yml is not defined

- name: Create dns secret file
  copy:
    dest: "{{ hs_workspace_secrets_dir }}/dns.yml"
    mode: 0640
    content: |-
      hs_dns_key_secret: "{{ tsig_key_sh.stdout }}"
  delegate_to: localhost
  become: false
  when: molecule_yml is not defined
