---
dependency:
  name: galaxy
  enabled: false
driver:
  name: containers
platforms:
  - name: debian
    groups:
      - hashistack
      - hashistack_sre
      - hashistack_masters
    image: galaxie-clans-debian:12
    log: true
    dockerfile: "../../../../molecule/platforms/Dockerfile-debian-12.j2"
    hostname: debian
    privileged: true
    pre_build_image: false
    pull: false
provisioner:
  name: ansible
  ansible_args:
    - "-e=@../../../../playbooks/group_vars/all.yml"
    - "-e=@../../vars/main.yml"
verifier:
  name: ansible
