---
- name: Verify DNS configuration
  hosts: all
  gather_facts: false
  tasks:
    - name: Extract DNS configuration from resolved.conf
      shell: cat /etc/systemd/resolved.conf | grep '^DNS='
      register: dns_config
      changed_when: false

    - name: Assert that DNS configuration is correct
      assert:
        that:
          - "'DNS=127.0.0.1' in dns_config.stdout"
        fail_msg: "DNS configuration is incorrect"
        success_msg: "DNS configuration is correct"