FROM debian:11-slim
WORKDIR /opt/cmc
COPY . ./
RUN apt update \
    && apt install -y make sudo python3-apt apt-transport-https \
    && make install-requirements prepare
RUN curl -s -L "https://releases.hashicorp.com/terraform/1.3.8/terraform_1.3.8_linux_amd64.zip" -o /tmp/terraform_1.3.8.zip && \
    unzip /tmp/terraform_1.3.8.zip -d /usr/local/bin/ && \
    chmod +x /usr/local/bin/terraform && \
    rm -f /tmp/terraform_1.3.8.zip
