---
- name: Create prometheus system group
  group:
    name: prometheus
    system: true
    state: present

- name: Create prometheus system user
  user:
    name: prometheus
    system: true
    shell: "/usr/sbin/nologin"
    group: prometheus
    createhome: false
    home: "{{ prometheus_db_dir }}"

- name: Create prometheus data directory
  file:
    path: "{{ prometheus_db_dir }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755

- name: Create prometheus configuration directories
  file:
    path: "{{ prometheus_config_dir }}"
    state: directory
    owner: root
    group: prometheus
    mode: 0770

- name: Unarchive Prometheus archive
  unarchive:
    src: "/var/cache/{{ __prometheus_download_file }}"
    dest: "/tmp/"
    remote_src: true

- name: Propagate prometheus binaries
  copy:
    src: "/tmp/{{ __prometheus_file_name }}/prometheus"
    dest: "{{ _prometheus_binary_install_dir }}/prometheus"
    mode: 0755
    owner: root
    group: root
    remote_src: true
  notify:
    - restart prometheus

- name: Propagate promtool binaries
  copy:
    src: "/tmp/{{ __prometheus_file_name }}/promtool"
    dest: "{{ _prometheus_binary_install_dir }}/promtool"
    mode: 0755
    owner: root
    group: root
    remote_src: true

- name: Create systemd service unit
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart prometheus
