---
- name: "Load common_vars role variables"
  import_role:
    name: "common_vars"
  tags:
    - always

- name: Load os-specific vars
  include_vars: "{{ _current_os_vars }}"
  with_first_found:
    - skip: true
      files: "{{ __hs_role_vars_precedence }}"
  loop_control:
    loop_var: _current_os_vars
  when:
    - ansible_distribution is defined
    - ansible_distribution | length > 0
  tags: always

