---
- hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Recursively remove directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ hs_workspace_host_vars_dir }}"
        - "{{ hs_workspace_group_vars_root_dir }}"
