---
- name: Converge Vault
  hosts: all
  gather_facts: yes
   
  roles:
    - "vault"

- name: Configure Vault
  ansible.builtin.import_playbook: "../../playbooks/01_vault_config.yml"
  vars:
    vault_public_cluster_address: "localhost:8200"

- name: Converge Consul
  hosts: all
  gather_facts: yes

  vars:
    consul_bootstrap_expect: 1
    local_node_address: 127.0.0.1
    ansible_default_ipv4:
      address: 127.0.0.1

  pre_tasks:
    - name: ReLoad workspace vars
      include_vars:
        dir: "{{ hs_workspace_group_vars_dir }}"
        ignore_unknown_extensions: true
   
  roles:
    - "consul"

- name: Configure Consul
  ansible.builtin.import_playbook: "../../playbooks/02_consul_config.yml"
  vars:
    consul_public_cluster_address: "localhost:8501"

- name: Converge Nomad
  hosts: all
  gather_facts: yes

  vars:
    public_domain: localhost
    nomad_node_fqdn: localhost
    nomad_bootstrap_expect: 1

  pre_tasks:
    - name: ReLoad workspace vars
      include_vars:
        dir: "{{ hs_workspace_group_vars_dir }}"
        ignore_unknown_extensions: true

  roles:
    - "envoy"
    - "nomad"
