---
driver:
  name: containers
platforms:
  - name: debian
    groups: 
      - molecule
      - molecule_sre
      - molecule_cluster
      - molecule_masters
      - molecule_minions
    image: "galaxie-clans-debian:11"
    log: true
    dockerfile: Dockerfile.j2
    hostname: debian
    privileged: true
    pre_build_image: false
    pull: false
    published_ports:
      - "127.0.0.1:22000:22/tcp"
      - "127.0.0.1:8200:8200/tcp"
      - "127.0.0.1:8501:8501/tcp"
      - "127.0.0.1:4646:4646/tcp"

provisioner:
  name: "ansible"
  playbooks:
    prepare: "$MOLECULE_COMMONS_DIR/prepare.yml"
  ansible_args:
    - "-e hs_workspace_root=${MOLECULE_SCENARIO_DIRECTORY}"
    - "-e tf_action=apply"
  inventory:
    links:
      group_vars: "../../playbooks/group_vars/"
  env:
    HS_WORKSPACE: molecule
    HS_PARENT_DOMAIN: localdomain

verifier:
  name: ansible
dependency:
  name: galaxy
  enabled: false
