---
driver:
  name: containers
platforms:
  - name: debian
    groups: 
      - molecule_platform
      - molecule_masters
      - molecule_minions
    image: "galaxie-clans-debian:11"
    log: True
    dockerfile: Dockerfile.j2
    hostname: debian
    privileged: yes
    pre_build_image: false
    pull: false
    published_ports:
      - "127.0.0.1:22000:22/tcp"
      - "127.0.0.1:8200:8200/tcp"

provisioner:
  name: "ansible"
  playbooks:
    prepare: "$MOLECULE_COMMONS_DIR/prepare.yml"
  ansible_args:
    - "-e hs_workspace_root=${MOLECULE_SCENARIO_DIRECTORY}"
    - "-e moleculed=yes"
    - "-e tf_action=apply"
  inventory:
    links:
      group_vars: "../../playbooks/group_vars/"
  env:
    ANSIBLE_COLLECTIONS_PATHS: "${ANSIBLE_COLLECTIONS_PATHS}"
    ANSIBLE_ROLES_PATH: "${ANSIBLE_ROLES_PATH}"
    HS_WORKSPACE: molecule

verifier:
  name: ansible
dependency:
  name: galaxy
  enabled: False
