---
- name: Install grafana
  apt:
    name: "{{ packages_list }}"
    state: present

- name: Enable and start grafana service
  service:
    name: grafana-server
    enabled: true
    state: started

