---
- name: Create loki user
  user:
    name: loki
    shell: /bin/false
    create_home: false

- name: Add grafana repo
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana

- name: Install loki
  apt:
    name: "loki={{ hs_loki_version }}"
    state: present
