---
- name: Create promtail user
  user:
    name: promtail
    groups: adm
    shell: /bin/false
    create_home: false

- name: Add grafana repo
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana

- name: Install promtail
  apt:
    name: "promtail={{ hs_loki_version }}"
    state: present

