---
- name: Prepare
  include_tasks: _prepare.yml
  tags:
    - prepare
    - online
    - loki

- name: Add grafana repo
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana
    update_cache: false

- name: Install Loki
  include_tasks: _install.yml
  when: inventory_hostname in groups['hashistack_sre']
  tags:
    - install
    - loki

- name: Configure
  include_tasks: _configure.yml
  when: inventory_hostname in groups['hashistack_sre']
  tags:
    - configure
    - loki

- name: Install Promtail
  include_tasks: _install_promtail.yml
  tags:
    - install
    - promtail

- name: Configure promtail
  include_tasks: _configure_promtail.yml
  tags:
    - configure
    - promtail

