---
- name: "Load collection vars"
  import_role:
    name: "common_vars"
  tags:
    - always

- name: "Load role vars"
  include_vars: "{{ _current_os_vars }}"
  with_first_found:
    - skip: true
      files: "{{ __hs_role_vars_precedence }}"
      paths: "{{ role_path }}/vars"
  loop_control:
    loop_var: _current_os_vars
  tags: always

- name: Execute os-specific tasks
  include_tasks: "{{ _current_os_tasks }}"
  with_first_found:
    - skip: true
      files: "{{ __hs_role_tasks_precedence }}"
      paths: "{{ role_path }}/tasks"
  loop_control:
    loop_var: _current_os_tasks
  tags: always

- name: Flush before leaving
  meta: flush_handlers
  tags: always
