---
__prometheus_file_name: "prometheus-{{ prometheus_version }}.linux-amd64"
__prometheus_download_url: "https://github.com/prometheus/prometheus/releases/download/"
__prometheus_download_link: "{{ __prometheus_download_url }}v{{ prometheus_version }}/{{ __prometheus_file_name }}.tar.gz"
__prometheus_download_file: "{{ __prometheus_file_name }}.tar.gz"
_prometheus_binary_install_dir: "/usr/local/bin/"
