variable "domain" {}
variable "consul_address" {}
variable "nomad_address" {}
variable "datacenter" {}
variable "dns_container_resolver" {}
variable "ca_file" {}
variable "dns_server" {}
variable "key_name" {}
variable "key_secret" {}
variable "key_algorithm" {}
