---
- name: Core Bootstrap
  ansible.builtin.import_playbook: "../../playbooks/00_core_bootstrap.yml"
  vars:
    _local_host_vars_dir_molecule: "{{ hs_workspace_host_vars_dir }}"
    clan_host_caretaker_password_file: "{{ hs_workspace_host_vars_dir }}/test.password"
    clan_host_caretaker_default_private_key_file: "{{ hs_workspace_host_vars_dir }}/test.key"
    clan_host_caretaker_default_key_dir: "{{ hs_workspace_host_vars_dir }}"

- name: Core Setup DNS
  ansible.builtin.import_playbook: "../../playbooks/00_core_setup_dns.yml"

- name: Core Reverse Proxy
  ansible.builtin.import_playbook: "../../playbooks/hs_rproxy.yml"
  vars:
    rproxy_enable: true

- name: Install Vault
  hosts: all
  gather_facts: true
  pre_tasks:
    - name: Reload workspace vars
      include_vars:
        dir: "{{ hs_workspace_group_vars_dir }}"
        ignore_unknown_extensions: true
  roles:
    - "vault"

- name: Configure Vault
  ansible.builtin.import_playbook: "../../playbooks/01_vault_config.yml"
  vars:
    vault_use_custom_ca: true

- name: Install Consul
  hosts: hashistack_masters
  gather_facts: true
  pre_tasks:
    - name: Reload workspace vars
      include_vars:
        dir: "{{ hs_workspace_group_vars_dir }}"
        ignore_unknown_extensions: true
  roles:
    - "consul"
    - "envoy"

- name: Install Consul
  hosts: "hashistack_minions:hashistack_sre"
  gather_facts: true
  pre_tasks:
    - name: Reload workspace vars
      include_vars:
        dir: "{{ hs_workspace_group_vars_dir }}"
        ignore_unknown_extensions: true
  roles:
    - name: "consul"
      vars:
        consul_role_do_configuration: false
    - "envoy"

- name: Configure Consul
  ansible.builtin.import_playbook: "../../playbooks/02_consul_config.yml"
  vars:
    consul_use_custom_ca: true
    pki_root_certificate_b64: "{{ (lookup('file', hs_workspace_secrets_dir + '/tf_vault_config.yml') | from_yaml).pki_root_certificate_b64 }}"

# - name: Install Nomad
#   hosts: all
#   gather_facts: true
#   pre_tasks:
#     - name: Reload workspace vars
#       include_vars:
#         dir: "{{ hs_workspace_group_vars_dir }}"
#         ignore_unknown_extensions: true
#   roles:
#     - "rtnp.galaxie_clans.container"
#     - "nomad"
