---
driver:
  name: containers

provisioner:
  name: "ansible"
  ansible_args:
    - "-e=@${MOLECULE_SCENARIO_DIRECTORY}/defaults/vars.yml"
  inventory:
    links:
      group_vars: "../../playbooks/group_vars/"
  env:
    ANSIBLE_COLLECTIONS_PATHS: "${ANSIBLE_COLLECTIONS_PATHS}"
    ANSIBLE_ROLES_PATH: "${ANSIBLE_ROLES_PATH}"

verifier:
  name: ansible

dependency:
  name: galaxy
  enabled: false

platforms:
  - name: molecule-sre
    groups:
      - hashistack
      - hashistack_sre
    image: "galaxie-clans-debian:11"
    log: true
    dockerfile: Dockerfile.j2
    hostname: molecule-sre
    privileged: true
    pre_build_image: false
    pull: false
    etc_hosts: "{'molecule-sre.molecule.localdomain':'127.0.0.1'}"
    networks:
      - name: molecule
        ipv4_address: 172.20.0.10
    docker_networks:
      - name: molecule
        ipam_config:
          - subnet: '172.20.0.0/24'
            gateway: '172.20.0.254'
  - name: molecule-master-01
    groups:
      - hashistack
      - hashistack_cluster
      - hashistack_masters
    image: "galaxie-clans-debian:11"
    log: true
    dockerfile: Dockerfile.j2
    hostname: molecule-master-01
    privileged: true
    pre_build_image: false
    pull: false
    networks:
      - name: molecule
        ipv4_address: 172.20.0.11
    published_ports:
      - "127.0.0.1:8200:8200/tcp"
      - "127.0.0.1:8501:8501/tcp"
      - "127.0.0.1:4646:4646/tcp"
  - name: molecule-master-02
    groups:
      - hashistack
      - hashistack_cluster
      - hashistack_masters
    image: "galaxie-clans-debian:11"
    log: true
    dockerfile: Dockerfile.j2
    hostname: molecule-master-02
    privileged: true
    pre_build_image: false
    pull: false
    networks:
      - name: molecule
        ipv4_address: 172.20.0.12
  - name: molecule-master-03
    groups:
      - hashistack
      - hashistack_cluster
      - hashistack_masters
    image: "galaxie-clans-debian:11"
    log: true
    dockerfile: Dockerfile.j2
    hostname: molecule-master-03
    privileged: true
    pre_build_image: false
    pull: false
    networks:
      - name: molecule
        ipv4_address: 172.20.0.13
  - name: molecule-minion-01
    groups:
      - hashistack
      - hashistack_cluster
      - hashistack_minions
    image: "galaxie-clans-debian:11"
    log: true
    dockerfile: Dockerfile.j2
    hostname: molecule-minion-01
    privileged: true
    pre_build_image: false
    pull: false
    networks:
      - name: molecule
        ipv4_address: 172.20.0.21
  - name: molecule-minion-02
    groups:
      - hashistack
      - hashistack_cluster
      - hashistack_minions
    image: "galaxie-clans-debian:11"
    log: true
    dockerfile: Dockerfile.j2
    hostname: molecule-minion-02
    privileged: true
    pre_build_image: false
    pull: false
    networks:
      - name: molecule
        ipv4_address: 172.20.0.22
  - name: molecule-minion-03
    groups:
      - hashistack
      - hashistack_cluster
      - hashistack_minions
    image: "galaxie-clans-debian:11"
    log: true
    dockerfile: Dockerfile.j2
    hostname: molecule-minion-03
    privileged: true
    pre_build_image: false
    pull: false
    networks:
      - name: molecule
        ipv4_address: 172.20.0.23
