---
- name: "Apply"
  debug:
    msg: "Starting apply phase"
    verbosity: 1

- name: "APPLY - Create a dedicated keypair"
  community.crypto.openssh_keypair:
    path: "{{ hs_stage0_private_key_file }}"
    type: ed25519

- name: "APPLY - Copy terraform sources"    # noqa risky-file-permissions
  copy:
    src: "{{ __hs_stage0_terraform_module }}/"
    dest: "{{ __hs_stage0_terraform_module_work_dir }}/"

- name: "Terraform {{ tf_action }}"
  include_tasks: _terraform.yml
  tags:
    - tf

- name: "APPLY - Terraform output extract"
  set_fact:
    sre_ipv4: "{{ tf_result.outputs.sre_ipv4.value }}"
    sre_ipv6: "{{ tf_result.outputs.sre_ipv6.value }}"
    current_ssh_user: "{{ tf_result.outputs.raw_ssh_user.value }}"
  tags:
    - outputs
    - molecule-notest

- name: "APPLY - Terraform output extract"
  set_fact:
    masters_ipv4: "{{ tf_result.outputs.masters_ipv4.value }}"
    minions_ipv4: "{{ tf_result.outputs.minions_ipv4.value }}"
    private_network_id: "{{ tf_result.outputs.private_network_id.value }}"
    bastion_ipv4: "{{ tf_result.outputs.bastion_ipv4.value }}"
    bastion_port: "{{ tf_result.outputs.bastion_port.value }}"
  when:
    - hs_archi == 'multi'
  tags:
    - outputs
    - molecule-notest

- name: "Add hosts to ssh config"
  blockinfile:
    path: "{{ hs_workspace_root }}/ssh.cfg"
    state: present
    create: true
    mode: 0640
    marker: "{{ __hs_stage0_block_marker }}"
    block: |
      {{ lookup('template', hs_archi + '/_ssh_cfg.j2') }}
  tags:
    - outputs

- name: "Add hosts to inventory"
  blockinfile:
    path: "{{ hs_workspace_root }}/inventory"
    state: present
    create: true
    mode: 0640
    marker: "{{ __hs_stage0_block_marker }}"
    block: |
      {{ lookup('template', hs_archi + '/_inventory.j2') }}
  tags:
    - outputs
    - molecule-notest

- name: "Render 'hashistack' group vars"
  template:
    src: "{{ hs_archi }}/out.stage0.hashistack.yml.j2"
    dest: "{{ hs_workspace_group_vars_dir }}/out.stage0.hashistack.yml"
    mode: 0640
  tags:
    - outputs

- name: "Render 'hashistack_sre' group vars"
  template:
    src: "multi/out.stage0.hashistack_sre.yml.j2"
    dest: "{{ hs_workspace_sre_group_vars_dir }}/out.stage0.hashistack_sre.yml"
    mode: 0640
  when: hs_archi == 'multi'
  tags:
    - outputs
