---
- name: "Check for terraform module dir"
  stat:
    path: "{{ __hs_stage0_terraform_module_work_dir }}"
  register: _tf_module
  tags:
    - tf

- name: "Do Terraform {{ tf_action }}"
  cloud.terraform.terraform:
    project_path: "{{ __hs_stage0_terraform_module_work_dir }}"
    state: "{{ __hs_stage0_state }}"
    force_init: "{{ hs_tf_init | default(true) }}"
    provider_upgrade: "{{ hs_tf_provider_upgrade | default(true) }}"
    workspace: "{{ hs_stage0_name }}"
    variables:
      ssh_public_key_file: "{{ hs_stage0_private_key_file }}.pub"
      instance_type: "{{ hs_stage0_instance_type }}"
      instance_image: "{{ hs_stage0_instance_image }}"
  register: tf_result
  when: _tf_module.stat.exists
  tags:
    - tf
    - molecule-notest
