---
- name: Prepare
  include_tasks:
    file: "{{ role_path }}/tasks/common/_prepare.yml"
    apply:
      tags: prepare
  tags:
    - prepare
    - online

- name: Install
  include_tasks:
    file: "{{ role_path }}/tasks/common/_install.yml"
    apply:
      tags: install
  tags:
    - install
    - online

- name: Configure
  include_tasks:
    file: "{{ role_path }}/tasks/common/_configure.yml"
    apply:
      tags: configure
  when: __hs_consul_is_master
  tags:
    - configure

- name: Flush
  meta: flush_handlers
