---
#
# ```{include} ../../../../roles/prometheus/README.md
# ```
#
# ## Role defaults

hs_prometheus_scrape_configs: []

hs_prometheus_cli_args: >-
  --enable-feature=remote-write-receiver


prometheus_local_cache_dir: "{{ hs_workspace_root }}"

prometheus_version: "2.42.0"