---
- name: Validation
  hosts: "{{ lookup('env', 'HS_WORKSPACE') }}"
  become: true
  gather_facts: true

  tasks:
    - name: Assert every host can reach Internet
      community.general.ipify_facts:

    - name: Assert that master group is child of platform group
      assert:
        that:
          - >-
            (groups[hs_workspace + '_masters'] | intersect(groups[hs_workspace + '']))
            == groups[hs_workspace + '_masters']
        msg: >-
          Inventory group malformed: {{ hs_workspace }}_masters should a child of {{ hs_workspace }}

    - name: Assert that minion group is child of platform group
      assert:
        that:
          - >-
            (groups[hs_workspace + '_minions'] | intersect(groups[hs_workspace + '']))
            == groups[hs_workspace + '_minions']
        msg: >-
          Inventory group malformed: {{ hs_workspace }}_minions should a child of {{ hs_workspace }}
