---
- name: Host metrics agent
  hosts: "{{ lookup('env', 'HS_WORKSPACE') }}_platform"
  become: true
  gather_facts: true
  roles:
    - role: "rtnp.galaxie_clans.monitor"

- name: Collect and Present
  hosts: "{{ lookup('env', 'HS_WORKSPACE') }}"
  become: true
  gather_facts: true

  roles:
    - role: "cloudalchemy.prometheus"
    - role: "cloudalchemy.grafana"

- name: Prom and Graf install
  hosts: "{{ lookup('env', 'HS_WORKSPACE') }}_platform"
  tags:
    - consul
  become: true
  gather_facts: true
  tasks:
    - copy:
        dest: /etc/consul.d/consul.api.json
        content: |-
          {
            "service": {
              "name": "consul_api",
              "tags": [
                "platform"
              ],
              "port": 8501,
              "address": "{{ local_node_address }}"
            }          
          }

    - copy:
        dest: /etc/consul.d/node_exporter.service.json
        content: |-
          {
            "service": {
              "name": "netdata_exporter",
              "tags": [
                "prometheus"
              ],
              "port": 19999,
              "address": "{{ local_node_address }}"
            }          
          }

    - service:
        name: consul
        state: restarted
