---
- import_playbook: rtnp.galaxie_clans.acme_rotate_certificates
  vars:
    scope: "hashistack_sre[0]"
    acme_nsupdate_key_secret: "{{ hs_dns_key_secret }}"
    acme_nsupdate_host: "{{ public_ipv4 }}"

- hosts: "hashistack_sre[0]"
  become: true
  gather_facts: false

  tasks:
    - name: Get certificate
      fetch:
        src: "/etc/ssl/private/*.{{ public_domain }}.{{ _current_part.extension }}"
        dest: "{{ _current_part.dest }}"
        flat: true
      loop:
        - extension: crt
          dest: "{{ vault_node_cert }}"
        - extension: "key"
          dest: "{{ vault_node_cert_private_key }}"
        - extension: "fullchain.crt"
          dest: "{{ vault_node_cert_fullchain }}"
      loop_control:
        loop_var: _current_part
      tags:
        - fetch
