---
- name: Stage 2.1 - Install consul
  hosts: hashistack
  become: true
  gather_facts: true

  roles:
    - role: "envoy"
    - role: "consul"

  tasks:
    - name: Include vault-sidecar role if required
      include_role:
        name: vault-sidecar
      when: hs_install_vault_sidecar | bool
     