---
- name: Install consul masters
  hosts: "hashistack_masters"
  become: true
  gather_facts: true

  roles:
    - role: "envoy"
    - role: "consul"

- name: Install consul minions
  hosts: "hashistack_minions:hashistack_sre"
  become: true
  gather_facts: true

  roles:
    - role: "envoy"
    - role: "consul"
      vars:
        consul_role_do_configuration: false

