---
- name: "[DANGER ZONE] Flush all data from vault masters"
  hosts: hashistack_masters
  become: true
  gather_facts: false

  vars:
    force_flush: false

  tasks:
    - name: "Load vault role variables"
      import_role:
        name: "vault_vars"

    - name: "Load secret dir"
      include_vars:
        dir: "{{ hs_vault_local_secret_dir }}"
        ignore_unknown_extensions: true
      no_log: true

    - name: Stop vault
      systemd:
        name: vault
        state: stopped
      when: force_flush

    - name: Delete all vault data
      file:
        path: /opt/vault/data
        state: absent
      when: force_flush

    - name: Recreate vault data dir
      file:
        path: /opt/vault/data
        state: directory
        owner: vault
        group: vault
        mode: 0750
      when: force_flush

    - name: Flush local root_vault
      file:
        path: "{{ hs_vault_local_secret_dir }}/root_vault.yml"
        state: absent
      delegate_to: localhost
      become: false
