---
- name: Restart networking
  systemd:
    name: "{{ hs_stage1_dns_network_service }}"
    state: restarted
    enabled: true
  when: molecule_yml is not defined
  tags:
    - restart_networking

- name: Restart resolved
  systemd:
    name: "systemd-resolved"
    state: restarted
    enabled: true
  when: molecule_yml is not defined
  tags:
    - restart_networking
