---
- name: "Modify data path in grafana.ini"
  ini_file:
    path: /usr/bin/grafana-v{{ hs_grafana_version }}/conf/defaults.ini
    section: "paths"
    option: "data"
    value: "/opt/grafana"
    backup: "yes"

- name: "Enable and start grafana service"
  service:
    name: "grafana-server"
    enabled: true
    state: started

- name: "Wait for Grafana endpoint"
  delegate_to: localhost
  run_once: true
  become: false
  uri:
    url: "{{ hs_grafana_url }}"
    ca_path: "{{ __hs_grafana_custom_ca_or_omit }}"
  register: _hs_grafana_ping
  until: _hs_grafana_ping.status == 200
  retries: 30
  delay: 10

- name: "Initial admin setup"
  include_tasks:
    file: "{{ role_path }}/tasks/__set_admin_pass.yml"
  when:
    - hs_grafana_password is not defined

- name: "Grafana API and dashboard setup"
  include_tasks:
    file: "{{ role_path }}/tasks/__service_setup.yml"
  when:
    - hs_grafana_key is not defined

