---
- name: "Prepare"
  include_tasks:
    file: "_prepare.yml"
    apply:
      tags: prepare
  tags:
    - prepare
    - online

- name: "Install"
  include_tasks:
    file: "_install.yml"
    apply:
      tags: install
  tags:
    - install

- name: "Configure"
  include_tasks:
    file: "_configure.yml"
    apply:
      tags: configure
  tags:
    - configure

