---
- name: Verify
  hosts: all
  gather_facts: true

  vars:
    docker_ssh_ports:
      Debian: "22000"

  tasks:
    - name: Validate SSH connection for caretaker
      raw: >-
        ssh 127.0.0.1
        -o User={{ glxclans_host_service_user_name }}
        -o Port={{ docker_ssh_ports[ansible_os_family] }}
        -o IdentityFile={{ glxclans_host_service_user_default_key_dir }}/{{ inventory_hostname }}.key
        -o StrictHostKeyChecking=no
        -o UserKnownHostsFile=/dev/null
        -o IdentitiesOnly=yes
        echo "connected"
      timeout: 25
      register: _caretaker_ssh_connect
      delegate_to: localhost

    - name: Activate Vault
      service:
        name: vault
        state: started
        enabled: true
      register: vault_service_status

    - name: Vault is started and enabled
      assert:
        that:
          - vault_service_status is not changed

    - name: Activate Consul
      service:
        name: consul
        state: started
        enabled: true
      register: consul_service_status

    - name: Consul is started and enabled
      assert:
        that:
          - consul_service_status is not changed

    - name: Activate Nomad
      service:
        name: nomad
        state: started
        enabled: true
      register: nomad_service_status

    - name: Nomad is started and enabled
      assert:
        that:
          - nomad_service_status is not changed
