---
dependency:
  name: galaxy
  enabled: false
driver:
  name: containers
platforms:
  - name: debian
    groups:
      - hashistack
      - hashistack_sre
      - hashistack_masters
    image: galaxie-clans-debian:11
    log: true
    dockerfile: "../../../../molecule/platforms/Dockerfile.j2"
    hostname: debian
    privileged: true
    pre_build_image: false
    pull: false
provisioner:
  name: ansible
  ansible_args:
    - "-e=@../../playbooks/group_vars/all.yml"
    - "-e=@../../molecule/vars/main.yml"
verifier:
  name: ansible
